# Generated by Django 4.2.6 on 2023-10-28 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vacancies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_wage', models.PositiveIntegerField(verbose_name='Доход от')),
                ('grade', models.CharField(choices=[('IN', 'Intern'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('LD', 'Lead')], max_length=2, verbose_name='Грейд')),
                ('work_format', models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='Формат работы')),
                ('schedule', models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='График работы')),
                ('currency', models.CharField(choices=[('RUB', '₽'), ('DOL', '$'), ('EURO', '€'), ('UAH', '₴')], max_length=5, verbose_name='Валюта')),
                ('is_winner', models.BooleanField()),
                ('age', models.PositiveSmallIntegerField()),
                ('graduation_date', models.DateField()),
                ('contacts', models.CharField(max_length=150)),
                ('edu_status', models.PositiveSmallIntegerField(choices=[(1, 'Студент'), (2, 'Выпускник')])),
                ('work_status', models.PositiveSmallIntegerField(choices=[(1, 'Учебный'), (2, 'Релевантный'), (3, 'Около-релевантный')])),
                ('salary', models.IntegerField()),
                ('optional_description', models.TextField(verbose_name='Немного о себе')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Город')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
                ('title', models.CharField(max_length=150, verbose_name='Должность')),
                ('description', models.CharField(max_length=150, verbose_name='обязанности')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_wage', models.PositiveIntegerField(verbose_name='Доход от')),
                ('grade', models.CharField(choices=[('IN', 'Intern'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('LD', 'Lead')], max_length=2, verbose_name='Грейд')),
                ('work_format', models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='Формат работы')),
                ('schedule', models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='График работы')),
                ('currency', models.CharField(choices=[('RUB', '₽'), ('DOL', '$'), ('EURO', '€'), ('UAH', '₴')], max_length=5, verbose_name='Валюта')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Подробности')),
                ('responsibility', models.TextField(verbose_name='Обязанности')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('optional_requirements', models.TextField(verbose_name='Необязательные требования')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('selection_stages', models.TextField(verbose_name='Этапы отбора')),
                ('max_wage', models.PositiveIntegerField(verbose_name='Доход до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Архивная')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=models.SET(vacancies.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy', to='vacancies.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_test_tasks', to='vacancies.applicant', verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_test_tasks', to='vacancies.vacancy', verbose_name='Рекрутер')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.language')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='vacancies.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_interviews', to='vacancies.applicant', verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_interviews', to='vacancies.vacancy', verbose_name='Рекрутер')),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_wage', models.PositiveIntegerField(verbose_name='Доход от')),
                ('grade', models.CharField(choices=[('IN', 'Intern'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('LD', 'Lead')], max_length=2, verbose_name='Грейд')),
                ('work_format', models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='Формат работы')),
                ('schedule', models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='График работы')),
                ('currency', models.CharField(choices=[('RUB', '₽'), ('DOL', '$'), ('EURO', '€'), ('UAH', '₴')], max_length=5, verbose_name='Валюта')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('optional_description', models.TextField(verbose_name='Немного о себе')),
                ('salary', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cv', to='vacancies.city', verbose_name='Город')),
                ('expirience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.expirience')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.course'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant', to='vacancies.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Отклик'), (2, 'Кандидат'), (3, 'Назначить интервью'), (4, 'Отправить тестовое'), (5, 'Тех. собеседование'), (6, 'Собеседование с руководителем'), (7, 'Тестовое задание'), (8, 'Отказ'), (9, 'Оффер'), (10, 'Отправить отказ'), (11, 'Отправить оффер')])),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_responses', to='vacancies.applicant', verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_responses', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'unique_together': {('applicant', 'vacancy')},
            },
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.CheckConstraint(check=models.Q(('min_wage__lte', models.F('max_wage')), ('max_wage__exact', 0), _connector='OR'), name='check_min_wage_less_than_max_wage'),
        ),
        migrations.AlterUniqueTogether(
            name='testtask',
            unique_together={('applicant', 'vacancy')},
        ),
        migrations.AlterUniqueTogether(
            name='languagelevel',
            unique_together={('language', 'vacancy', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('applicant', 'vacancy')},
        ),
    ]
