# Generated by Django 4.2.6 on 2023-10-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Язык')),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='language',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='language_level',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='language',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='language_level',
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', ''), ('A2', ''), ('B1', ''), ('B2', ''), ('C1', ''), ('C2', '')], max_length=2)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.language')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
        ),
    ]
