# Generated by Django 4.2.6 on 2023-10-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_languagelevel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='min_wage',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='min_wage',
        ),
    ]
