# Generated by Django 4.2.6 on 2023-10-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_languagelevel_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagelevel',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='vacancies.vacancy'),
        ),
    ]
