# Generated by Django 4.2.6 on 2023-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_remove_applicant_schedule_remove_cv_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='expirience',
            field=models.CharField(choices=[('LOW', '0'), ('MED', '1-3'), ('HI', '3-6'), ('HIP', '6+')], default=1, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
