# Generated by Django 4.2.6 on 2023-10-25 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0004_alter_languagelevel_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='is_remote_work',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_remote_work',
        ),
        migrations.AddField(
            model_name='cv',
            name='schedule',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], default='RM', max_length=5, verbose_name='График'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], default='RM', max_length=5, verbose_name='График'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('IN', 'Intern'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('LD', 'Lead')], max_length=2, verbose_name='Грейд')),
                ('min_wage', models.PositiveIntegerField(verbose_name='Доход от')),
                ('max_wage', models.PositiveIntegerField(verbose_name='Доход до')),
                ('experience', models.CharField(choices=[('LOW', '0'), ('MED', '1-3'), ('HI', '3-6'), ('HIP', '6+')], max_length=5, verbose_name='Опыт работы')),
                ('currency', models.CharField(choices=[('RUB', '₽'), ('DOL', '$'), ('EURO', '€'), ('UAH', '₴')], max_length=5, verbose_name='Валюта')),
                ('schedule', models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='График')),
                ('is_winner', models.BooleanField()),
                ('age', models.PositiveSmallIntegerField()),
                ('graduation_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.course')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant', to='vacancies.city', verbose_name='Город')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
