# Generated by Django 4.2.6 on 2023-10-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_vacancy_expirience'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='exp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vacancies.expirience'),
        ),
    ]
