# Generated by Django 4.2.6 on 2023-10-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_vacancyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyresponse',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='vacancies.vacancy', verbose_name='Рекрутер'),
        ),
    ]
