# Generated by Django 4.2.6 on 2023-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_applicant_exp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testtask',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testtask',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='testtask',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_count',
            field=models.PositiveSmallIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='test_task_count',
            field=models.PositiveSmallIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='TestTask',
        ),
    ]
