# Generated by Django 4.2.6 on 2023-10-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_vacancyresponse_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyresponse',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_responses', to='vacancies.applicant', verbose_name='Соискатель'),
        ),
        migrations.AlterField(
            model_name='vacancyresponse',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_responses', to='vacancies.vacancy', verbose_name='Рекрутер'),
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_test_tasks', to='vacancies.applicant', verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_test_tasks', to='vacancies.vacancy', verbose_name='Рекрутер')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_interviews', to='vacancies.applicant', verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_interviews', to='vacancies.vacancy', verbose_name='Рекрутер')),
            ],
        ),
    ]
