# Generated by Django 4.2.6 on 2023-10-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_testtask_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='response_base_count',
            field=models.PositiveSmallIntegerField(default=11),
            preserve_default=False,
        ),
    ]
