# Generated by Django 4.2.6 on 2023-10-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_vacancyresponse_applicant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('applicant', 'vacancy')},
        ),
        migrations.AlterUniqueTogether(
            name='testtask',
            unique_together={('applicant', 'vacancy')},
        ),
        migrations.AlterUniqueTogether(
            name='vacancyresponse',
            unique_together={('applicant', 'vacancy')},
        ),
    ]
