# Generated by Django 4.2.6 on 2023-10-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_applicant_response_base_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagelevel',
            unique_together={('language', 'vacancy')},
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2),
        ),
    ]
