# Generated by Django 4.2.6 on 2023-10-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_applicant_response_base_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagelevel',
            unique_together={('language', 'vacancy')},
        ),
    ]
