# Generated by Django 4.2.6 on 2023-10-26 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0009_alter_interview_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='province',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='province',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='applicant',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vacancies.language', verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vacancies.language', verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vacancies.language', verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Соискатель'),
        ),
    ]
