# Generated by Django 4.2.6 on 2023-10-30 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_alter_languagelevel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contacts',
            field=models.CharField(max_length=150, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.course', verbose_name='Пройденный курс'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='edu_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Студент'), (2, 'Выпускник')], verbose_name='Статус обучения'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='exp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vacancies.expirience', verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='graduation_date',
            field=models.DateField(verbose_name='Дата окончания курса'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='is_winner',
            field=models.BooleanField(verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='work_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Учебный'), (2, 'Релевантный'), (3, 'Около-релевантный')], verbose_name='Статус опыта работы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name='Уровень языка'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacancyresponse',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Отклик'), (2, 'Кандидат'), (3, 'Назначить интервью'), (4, 'Отправить тестовое'), (5, 'Тех. собеседование'), (6, 'Собеседование с руководителем'), (7, 'Тестовое задание'), (8, 'Отказ'), (9, 'Оффер'), (10, 'Отправить отказ'), (11, 'Отправить оффер')], verbose_name='Статус кандидата'),
        ),
    ]
