# Generated by Django 4.2.6 on 2023-10-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_rename_province_cv_city_rename_province_vacancy_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('duration', models.DurationField()),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
                ('title', models.CharField(max_length=150, verbose_name='Должность')),
                ('description', models.CharField(max_length=150, verbose_name='обязанности')),
            ],
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='max_wage',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='min_wage',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='max_wage',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='min_wage',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='experience',
        ),
        migrations.AddField(
            model_name='applicant',
            name='contacts',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='work_format',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], default=1, max_length=5, verbose_name='Форма работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='work_format',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], default=1, max_length=5, verbose_name='Форма работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], default=1, max_length=5, verbose_name='Форма работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='schedule',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='schedule',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='cv',
            name='expirience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vacancies.expirience'),
            preserve_default=False,
        ),
    ]
