# Generated by Django 4.2.6 on 2023-10-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_alter_applicant_age_alter_applicant_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='exp',
        ),
        migrations.DeleteModel(
            name='Cv',
        ),
        migrations.AddField(
            model_name='applicant',
            name='exp',
            field=models.ManyToManyField(to='vacancies.expirience', verbose_name='Опыт работы'),
        ),
    ]
