# Generated by Django 4.2.6 on 2023-10-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_remove_applicant_exp_delete_cv_applicant_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirience',
            name='description',
            field=models.CharField(max_length=1500, verbose_name='обязанности'),
        ),
    ]
