# Generated by Django 4.2.6 on 2023-10-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_expirience_rename_name_cv_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyresponse',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Отклик'), (2, 'Кандидат'), (3, 'Назначить интервью'), (4, 'Отправить тестовое'), (5, 'Тех. собеседование'), (6, 'Собеседование с руководителем'), (7, 'Тестовое задание'), (8, 'Отказ'), (9, 'Оффер'), (10, 'Отправить отказ'), (11, 'Отправить оффер')], default=1),
            preserve_default=False,
        ),
    ]
