# Generated by Django 4.2.6 on 2023-10-28 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_vacancyresponse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='edu_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Студент'), (2, 'Выпускник')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='work_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Учебный'), (2, 'Релевантный'), (3, 'Около-релевантный')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancyresponse',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_responses', to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
    ]
