# Generated by Django 4.2.6 on 2023-10-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_applicant_edu_status_applicant_work_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='lang',
        ),
    ]
