# Generated by Django 4.2.6 on 2023-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_remove_applicant_lang_remove_cv_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='min_wage',
            field=models.PositiveIntegerField(default=50000, verbose_name='Доход от'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='min_wage',
            field=models.PositiveIntegerField(default=50000, verbose_name='Доход от'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='work_format',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='Формат работы'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work_format',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='Формат работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(choices=[('FD', 'Полный день'), ('HB', 'Гибрид'), ('RM', 'Удалённая работа'), ('FX', 'Гибкий график')], max_length=5, verbose_name='Формат работы'),
        ),
    ]
