# Generated by Django 4.2.6 on 2023-10-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_remove_applicant_lang_remove_cv_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='expirience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vacancies.expirience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='optional_description',
            field=models.TextField(default=1, verbose_name='Немного о себе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
