# Generated by Django 4.2.6 on 2023-10-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_applicant_expirience_applicant_optional_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expirience',
            name='duration',
        ),
    ]
