# Generated by Django 4.2.6 on 2023-10-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_remove_applicant_expirience'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='expirience',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='vacancies.expirience'),
            preserve_default=False,
        ),
    ]
