# Generated by Django 4.2.6 on 2023-10-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0018_applicant_expirience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='expirience',
        ),
    ]
